const cameraDataFile = {
    // --------------------- Canon ----------------------
    "Canon": [
        "EOS300D",
        "EOS350D",
        "EOS400D",
        "EOS450D",
        "EOS500D",
        "EOS550D",
        "EOS600D",
        "EOS650D",
        "EOS700D",
        "EOS750D",
        "EOS760D",
        "EOS800D",
        "EOS850D",
        "EOS100D",
        "EOS200D",
        "EOS250D",
        "EOS1000D",
        "EOS1100D",
        "EOS1200D",
        "EOS1300D",
        "EOS1500D",
        "EOS3000D",
        "EOS D30",
        "EOS D60",
        "EOS 10D",
        "EOS 20D",
        "EOS 20Da",
        "EOS 30D",
        "EOS 40D",
        "EOS 50D",
        "EOS 60D",
        "EOS 60Da",
        "EOS 70D",
        "EOS 77D",
        "EOS 80D",
        "EOS 90D",
        "EOS 7D",
        "EOS 7D Mark II",
        "EOS 7D Mark III",
        "EOS 5D",
        "EOS 5D Mark II",
        "EOS 5D Mark III",
        "EOS 5D Mark IV",
        "EOS 5Ds",
        "EOS 5Ds R",
        "Eos 6D",
        "EOS 6D Mark II",
        "EOS-1D",
        "EOS-1Ds",
        "EOS-1D Mark II",
        "EOS-1Ds Mark II",
        "EOS-1D Mark II N",
        "EOS-1D Mark III",
        "EOS-1Ds Mark III",
        "EOS-1D Mark IV",
        "EOS-1D X",
        "EOS-1D X Mark II",
        "EOS-1D C",
        "EOS-1D X Mark III",
        "EOS M",
        "EOS M2",
        "EOS M3",
        "EOS M10",
        "EOS M5",
        "EOS M6",
        "EOS M6 Mark II",
        "EOS M100",
        "EOS M50",
        "EOS R",
        "EOS RP",
        "EOS Ra",
        "EOS R5",
        "EOS R6",
        "PXW-FS5 II",
        "PXW-FX9"
    ],
// --------------------- Sony ----------------------
    "Sony": [
        "a900",
        "a850",
        "a99",
        "a99 II",
        "a100",
        "a700",
        "a200",
        "a300",
        "a350",
        "a230",
        "a330",
        "a380",
        "a500",
        "a550",
        "a450",
        "a290",
        "a390",
        "a560",
        "a580",
        "a33",
        "a55",
        "a35",
        "a65",
        "a77",
        "a57",
        "a37",
        "a58",
        "a77 II",
        "a68",
        "NEX-3",
        "NEX-5",
        "NEX-C3",
        "NEX-5N",
        "NEX-7",
        "NEX-F3",
        "NEX-5R",
        "NEX-6",
        "NEX-3N",
        "NEX-5T",
        "a3000",
        "a7",
        "a7R",
        "a5000",
        "a6000",
        "a3500",
        "a7S",
        "a5100",
        "a7 II",
        "a7R II",
        "a7SII",
        "a6300",
        "a6500",
        "a9",
        "a7R III",
        "a7 III",
        "a6400",
        "a6600",
        "a6100",
        "a9 II",
        "a7c",
        "aQX1",
        "PXW-FS5 II",
        "PXW-FX9"
    ],

// --------------------- Nikon ----------------------
    "Nikon": [
        "1 J1",
        "1 V1",
        "2500",
        "4500HD",
        "3500",
        "5500HD",
        "1500 Classic",
        "1500",
        "2500",
        "4500HD",
        "3500",
        "5500HD",
        "1500 Classic",
        "1500",
        "2500",
        "4500HD",
        "3500",
        "5500HD",
        "1500 Classic",
        "1500",
        "2500",
        "4500HD",
        "3500",
        "5500HD",
        "1500 Classic",
        "1500",
        "2500",
        "4500HD",
        "3500",
        "5500HD",
        "1500 Classic",
        "1500",
        "2500",
        "4500HD",
        "3500",
        "5500HD",
        "1500 Classic",
        "1500",
        "2500",
        "4500HD",
        "3500",
        "5500HD",
        "1500 Classic",
        "1500",
        "2500",
        "4500HD",
        "3500",
        "5500HD"
    ],

// --------------------- Fujifilm ----------------------
    "Fujifilm": [
    "Rogue",
    "Sentra",
    "Murano",
    "Rogue Sport"
    ],

// --------------------- Olympus ----------------------
    "Olympus": [
    "Renegade",
    "Cherokee",
    "Compass",
    "Wrangler",
    "Grand Cherokee",
    "Gladiator",
    "Patriot"
    ],

// --------------------- Panasonic ----------------------
    "Panasonic": [
    "Charger",
    "Journey",
    "Grand Caravan",
    "Challenger",
    "Durango"
    ],

// --------------------- Leica ----------------------
    "Leica": [
    "Tundra",
    "Camry",
    "Corolla",
    "RAV4"
    ],

// --------------------- Hasslblad ----------------------
    "Hassleblad": [
    "124 Spider"
    ],

// --------------------- Iphone ----------------------
    "Iphone": [
    "Cooper S"
    ],

// --------------------- Android ----------------------
    "Android": [
    "Acadia",
    "Yukon XL",
    "Canyon",
    "Sierra 1500",
    "Terrain",
    "Sierra 2500HD",
    "Yukon",
    "Sierra 3500HD"
    ],

// --------------------- Other ----------------------
    "Other": [
    "Other"
    ]
    }

    export default cameraDataFile